### ISSUE TITLE
"invalid response." after "Success!" in Chromium

### ISSUE THREAD

**Issue by CyberShadow** [TecharoHQ/anubis#564]
Hi, thank you very much for Anubis!

I've just set it up for two websites on the same server:

- https://wiki.dlang.org/ - works perfectly.
- https://dsource.org/ :
  - In Firefox: works perfectly.
  - In Chomium: In a new private window, I see, in quick succession:
    1. "Making sure you're not a bot"
    2. "Success!"
    3. "Oh noes!" / "invalid response"
       - On this page, nothing happens if I click "Try again", but clicking "Go home" results in a "Success!" and successful website load.

Any idea what could be the problem?

Installed from `anubis_1.18.0_amd64.deb`.
Browser versions:
- Firefox 136.0.3
- Chromium 134.0.6998.165

**Comment by mikepayne02** [comment]
openwrt.org started working again with Chrome 136.0.7103.114 today, strange.

**Comment by Xe** [comment]
Do you have a dual stack internet connection?

**Comment by CyberShadow** [comment]
> Do you have a dual stack internet connection?

Yes, that must be it. Firefox is using IPv4 while Chromium is using IPv6.

**Comment by mikepayne02** [comment]
Confirmed, I was using a dual-stack network yesterday and now on an IPv4 only one it works.

**Comment by me-cfs** [comment]
I am getting this error as well on Safari ios

**Comment by Xe** [comment]
I'm going to implement a different challenge string creation method when I get off work today. I'm going to make something that operates off of client metadata without the remote IP address to see if that causes a reduction in the false rejection rate. I've been doing research on a fairly large dataset of HTTP requests sent to my infrastructure and I think I've found some patterns that can create a somewhat unique fingerprint without JavaScript in the mix.

```text
db> select count(*) as requests from cloud.requests;
```

| requests |
|---------:|
| 300655   |

I plan to do this in a few phases:

- [x] Document the `thr1` (Techaro HTTP Request Fingerprinting version 1) spec on my git server
- [ ] Make a pass at implementation, see what the collision rate is for requests from different ASNs
- [ ] Push as a PR to Anubis and deploy to a few sites to get a feeling for what it's like in practice

**Comment by CyberShadow** [comment]
Thank you, may I suggest to perhaps look into fixing the "Try again" button in this situation, as that seems like a low hanging fruit for UX improvement.

**Comment by Xe** [comment]
Fix it how? I'm not aware of it not working.

**Comment by CyberShadow** [comment]
As described in the issue description. Here's a video:

https://github.com/user-attachments/assets/5302257a-3405-48da-b27d-6f046ced95fd

**Comment by Xe** [comment]
I've implemented the THR1 spec in #616. Please give feedback.

**Comment by tycrek** [comment]
Using `ttl.sh/techaro/pr-616/anubis:24h`, still occasionally getting the "Invalid response" with behavior described above: clicking **Try again** doesn't appear to do anything; clicking **Go home** seems to make it work most of the time.

![Image](https://github.com/user-attachments/assets/f8115f82-a38e-4e62-9e6f-fcec08079b47)

**Comment by heliloop** [comment]
i am on dual stack and have the same problem in firefox and in chrome  (firefox uses ipv4, chome ipv6 - so not sure if it's dualstack related).

"try again" does nothing for me but "go home" does sometimes.

The way i test it is by simply deleting "techaro.lol-anubis-auth" cookie - my setup: nginx -> k8s ingress-nginx -> anubis -> app

tried eliminating first nginx w/o luck

what i noticed that after "success - oh noes" techaro.lol-anubis-auth cookie is not being set

From network
```
1.
GET REMOVED/
Set-Cookie
	techaro.lol-anubis-auth=; Path=/; Expires=Wed, 18 Jun 2025 09:52:52 GMT; Max-Age=0; SameSite=Lax
Set-Cookie
	techaro.lol-anubis-cookie-test-if-you-block-this-anubis-wont-work=f337b7186fe4a9c3e8cc7e728d07017541d5986409c8a661703414d14ccc9fc5; Path=/; Expires=Wed, 18 Jun 2025 10:23:52 GMT
X-Content-Type-Options
	nosniff
X-Frame-Options
	SAMEORIGIN
X-Robots-Tag
	noindex, nofollow
X-XSS-Protection
	1; mode=block

2.
GET https://REMOVED/.within.website/x/cmd/anubis/api/pass-challenge?response=0000a06e97d4e5977ebf03db4f21f12bd7446d77c3503a9a37851284f11beb32&nonce=25561&redir=https://REMOVED/&elapsedTime=523
Cookie
	techaro.lol-anubis-cookie-test-if-you-block-this-anubis-wont-work=f337b7186fe4a9c3e8cc7e728d07017541d5986409c8a661703414d14ccc9fc5
Set-Cookie
	techaro.lol-anubis-cookie-test-if-you-block-this-anubis-wont-work=; Path=/; Expires=Wed, 18 Jun 2025 09:52:53 GMT; Max-Age=0; SameSite=Lax
Set-Cookie
	techaro.lol-anubis-auth=; Path=/; Expires=Wed, 18 Jun 2025 09:52:53 GMT; Max-Age=0; SameSite=Lax
```

When it does work the pass-chalange looks like this:
```
GET https://REMOVED/.within.website/x/cmd/anubis/api/pass-challenge?response=0000f6221a0ed59a1939f25bf3bd33fa049667f26bd7576faa88417f46d6a4f5&nonce=48360&redir=https://REMOVED/&elapsedTime=1631
Cookie
  techaro.lol-anubis-cookie-test-if-you-block-this-anubis-wont-work=e3bc14fc2ac87d0eb29c65db7e4499e8b4799af7ee10e52d11608a302e19c107
Set-Cookie
	techaro.lol-anubis-cookie-test-if-you-block-this-anubis-wont-work=; Path=/; Expires=Wed, 18 Jun 2025 10:01:35 GMT; Max-Age=0; SameSite=Lax
Set-Cookie
	techaro.lol-anubis-auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhY3Rpb24iOiJDSEFMTEVOR0UiLCJjaGFsbGVuZ2UiOiJlM2JjMTRmYzJhYzg3ZDBlYjI5YzY1ZGI3ZTQ0OTllOGI0Nzk5YWY3ZWUxMGU1MmQxMTYwOGEzMDJlMTljMTA3IiwiZXhwIjoxNzUwODQ1NzU1LCJpYXQiOjE3NTAyNDA5NTUsIm5iZiI6MTc1MDI0MDg5NSwibm9uY2UiOiI0ODM2MCIsInBvbGljeVJ1bGUiOiJlZDU1ZThhMGJkZjcwNGM4NTFkY2RjMjQ3OWZmMTJlMjM1YzY1Y2Q0NjMwZGYwMTgwNGM4ZTgyMzZjMzU1NzE2IiwicmVzcG9uc2UiOiIwMDAwZjYyMjFhMGVkNTlhMTkzOWYyNWJmM2JkMzNmYTA0OTY2N2YyNmJkNzU3NmZhYTg4NDE3ZjQ2ZDZhNGY1In0.neNt61WX4Ch3wsHJsq-2EcpSjsGfGJLvAWqvq9-7lt-bEMFrmxuh-PDtvepZl3kSnr69Kpa-bBP7KW_s8qG3CQ; Path=/; Expires=Wed, 25 Jun 2025 10:02:35 GMT; SameSite=Lax
```

What I am also see in the logs when it fails
```
{"time":"2025-06-18T09:52:36.236353431Z","level":"WARN","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).PassChallenge","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":386},"msg":"user has cookies disable ││ d, this is not an anubis bug","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:139.0) Gecko/20100101 Firefox/139.0","accept_language":"en-GB,en;q=0.5","priority":"u=0, i","x-forwarded-for":"","x-real-ip":"192.168.1. ││ 110","check_result":{"name":"bot/generic-browser","rule":"CHALLENGE"}}
```

**Comment by Xe** [comment]
The root cause has been fixed in #711. This fix will be out in v1.20.0 soon.

**Comment by tycrek** [comment]
I'm still encountering this on v1.20.0 on multiple sites. Tested with Chromium 138.0.7204.49 and Librewolf 139.0.4-1. "Try again" still fails, "Go home" sometimes fixes it.

**Comment by heliloop** [comment]
I am sorry to report that the problem seems to be still there, chrome (ipv6) and firefox (ipv4)

```
GET https://REMOVED

# returns 200
# set-cookie
techaro.lol-anubis-auth=; Path=/; Expires=Sun, 29 Jun 2025 11:46:41 GMT; Max-Age=0; SameSite=Lax
# set-cookie
techaro.lol-anubis-cookie-test-if-you-block-this-anubis-wont-work=af9a16f77159805; Path=/; Expires=Sun, 29 Jun 2025 12:17:41 GMT

GET https://REMOVED/.within.website/x/cmd/anubis/api/pass-challenge?response=00df117f2aea881e623fe8c30fdc9ce907e50106469fd713657c0d8cacd52884&nonce=88&redir=REMOVED&elapsedTime=11
# retusns 403
```

**Comment by tycrek** [comment]
@Xe I've had enough users report problems that I just had to disable Anubis for now. How can I help with troubleshooting this? Or should we open a new issue at this point?

**Comment by Xe** [comment]
Hey,

Is there any common pattern? Chrome? Firefox? Multi-language? IPv4/IPv6 dual stack?

I don't have enough information to figure out what's going on.

**Comment by heliloop** [comment]
For me it doesn't look like problem with browser or ipv4/ipv6.  I tend to testing it by removing techaro.lol-anubis-auth cookie or going incognito.

I spent some time today and now I am not sure if the problem is related to anubis (at least in my case)

Versions:
* Chrome 137.0.7151.122 (Official Build) (arm64) 
* Chromium 114.0.5713.0 (Developer Build) (arm64) 
* Firefox 139.0.4
* Tor browser (firefox) 128.11.0esr

I have a website with anubis; the way you can access it is via internal or external domain name, something like mysite.internal.example.com and mysite.example.com - so the former is available only for internal users, the latter for the world.

The difference is, if I go via internal (mysite.internal.example.com) I am not able to reproduce the problem (k8s -> mysite).

When I go via external (mysite.example.com) - it break down quite easily like 30% (nginx -> k8s -> mysite)

The difference is additional nginx on the way when handling external traffic.  It's pretty standard reverse proxy configuration but it makes me think that maybe the headers are somehow mixed up between reverse proxy on k8s and edge reverse proxy (speculating after reading description of https://github.com/TecharoHQ/anubis/pull/711)

Going to try with edge nginx with out-of-the-box config and see how it works.

Do you have any idea how to debug it further?  And thank you for a great project 👏

**Comment by tycrek** [comment]
Chrome, Firefox, Librewolf. Single-language but en_CA rather than en_US. Myself, I'm just IPv4; my users I do not know.

I'm curious why the behavior of **Try again** and **Go home** are different... **Try again** never works for my users; **Go home** fixes it maybe 70% of the time.

We're using Caddy as our proxy server, also fairly standard, but applying these headers in transit:

```Caddyfile
	reverse_proxy localhost:8924 {
		header_up x-real-ip {remote_host}
		header_up x-http-version {http.request.proto}
	}
```

**Comment by Xe** [comment]
Okay, I have a complete rewrite of the challenge creation flow in #749. I think my core assumptions about browsers work with regards to how challenges were created is fundamentally incorrect. I assumed that my challenge creation method was idempotent, or that a single client hitting that route at time t0 to get string s0 would also get string s0 when hitting that route at time t1. This is apparently false and instead of fighting windmills trying to figure out why, I changed this to use a completely different flow.

Now Anubis generates a new challenge string based on 256 bytes of cryptographically random data. Anubis stores metadata about challenges (including the challenge string) in a Store. Right now the only Store is a simple in-memory data structure based on [decaymap](https://pkg.go.dev/github.com/TecharoHQ/anubis/decaymap). Before that PR merges, I will add storage backends for the following:

- [bbolt](https://github.com/etcd-io/bbolt), an embedded key/value store for Go programs
- [valkey](https://valkey.io/), the community fork of Redis

In addition, I think part of the reason this is stinging so bad is that there is a core UX flaw with this approach: the "success" screen doesn't actually mean "server accepted challenge", it means "client found a solution". I made #745 to remove that as a stopgap.

Hopefully this will stop the bleeding.

Thank you for bearing with me.

**Comment by Xe** [comment]
I think I have finally fixed this bug for good in #749.

If you use Anubis via Docker, please update to `ghcr.io/techarohq/anubis:main`. Please be sure to add a docker volume for [persistent storage on the disk](https://anubis.techaro.lol/docs/admin/policies#bbolt) mounted to `/data` and add the following to your configuration/policy file:

```yaml
store:
  backend: bbolt
  parameters:
    path: /data/anubis.bdb
```

If you use Docker compose, the end result could look like this:

```yaml
services:
  anubis:
    image: ghcr.io/techarohq/anubis:main
    pull_policy: always
    environment:
      BIND: ":8080"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://nginx"
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    ports:
      - 8080:8080
    volumes:
      - "./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
      - "anubis-data:/data"
  nginx:
    image: nginx
    volumes:
      - "./www:/usr/share/nginx/html"

volumes:
  anubis-data:
```

If this fixes the issue, I'm going to tag Anubis v1.21.0 this weekend. If not, comment here with information so we can all suffer together.
