### ISSUE TITLE
Access denied to gnome site ("oh noes")

### ISSUE THREAD

**Issue by amaanq** [TecharoHQ/anubis#960]
I'm not sure why, but I can't seem to access https://gitlab.gnome.org/GNOME/dconf. This is what I see on my end:

<img width="590" height="661" alt="Image" src="https://github.com/user-attachments/assets/8b7e86f5-2647-4880-bca4-b08892fb08ed" />

I'm on Linux (NixOS) using a Chromium based browser (Thorium) and haven't had this issue before with any site protected with anubis. Even now, other sites work fine (like dlang.org), so I'm not sure what's going on here. It seems like any site under https://gitlab.gnome.org is blocked for me.

**Comment by Xe** [comment]
Fixed in #944.

**Comment by iconoclasthero** [comment]
Still happening with Thorium on gitlab.gnome.org which is running Anubis version v1.22.0-pre1.
